# Generated by Django 3.0.3 on 2020-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='name',
            field=models.CharField(choices=[('Work', 'work')], default='work', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='slug',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
