# Generated by Django 3.0.3 on 2020-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20200705_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='name',
            field=models.CharField(choices=[('Work', 'work')], max_length=255, unique=True),
        ),
    ]
