# Generated by Django 3.0.3 on 2020-07-05 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0004_themes_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='themes',
            unique_together={('name', 'user', 'is_enabled')},
        ),
    ]
