# Generated by Django 3.0.3 on 2020-04-07 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField()),
                ('preview_image', models.FileField(upload_to='work-profiles/preview_images')),
                ('project_files', models.FileField(upload_to='work-profiles/project-files')),
                ('draft', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workprofile_workprofiles_related', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'WorkProfiles',
            },
        ),
        migrations.CreateModel(
            name='WorkProfileImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='work-profiles/images')),
                ('active', models.BooleanField(default=True)),
                ('work_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workprofiles', to='workprofile.WorkProfiles')),
            ],
        ),
    ]
