# Generated by Django 3.0.3 on 2020-04-07 15:53

from django.db import migrations, models
import workprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('workprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofileimages',
            name='image',
            field=models.FileField(upload_to=workprofile.models.upload_images_path),
        ),
        migrations.AlterField(
            model_name='workprofiles',
            name='preview_image',
            field=models.FileField(upload_to=workprofile.models.upload_preview_image_path),
        ),
        migrations.AlterField(
            model_name='workprofiles',
            name='project_files',
            field=models.FileField(upload_to=workprofile.models.upload_project_files_path),
        ),
        migrations.AlterField(
            model_name='workprofiles',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
